### ISSUE TITLE
learn to use grunt

### ISSUE THREAD

**Issue by diwu1989** [Kenadia/circular-progress-indicator#3]
http://gruntjs.com/

You can use this to automate parts of your workflow:
- coffeelinting
- compiling coffee -> js
- taking css -> adding vendor prefixing
- watching deveopment files and auto-compiling when things change
- live-reloading your browser as you develop

**Comment by Kenadia** [comment]
Thanks! That's awesome! I've added Grunt tasks for everything you mentioned.
